{
 "title": "Backend - Electronics Sell App",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"electronics-shop\", app=\"backend\"}[5m])) by (route, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Error Rate %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(http_requests_total{namespace=\"electronics-shop\", app=\"backend\", status_code=~\"5..\"}[5m])) or vector(0))\r\n    / sum(rate(http_requests_total{namespace=\"electronics-shop\", app=\"backend\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_request_duration_seconds_bucket{namespace=\"electronics-shop\", app=\"backend\"}[5m])) by (le, route)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\r\n  sum(rate(http_request_duration_seconds_bucket{namespace=\"electronics-shop\", app=\"backend\"}[5m])) by (le, route)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node.js Runtime - Event Loop delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{namespace=\"electronics-shop\", app=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node.js Runtime - V8 Heap %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * nodejs_heap_size_used_bytes{namespace=\"electronics-shop\", app=\"backend\"}\r\n    / nodejs_heap_size_total_bytes{namespace=\"electronics-shop\", app=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}